"""crops table

Revision ID: c9acd6a81033
Revises: 1cfecb9ed39c
Create Date: 2023-07-30 18:38:04.273774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9acd6a81033'
down_revision = '1cfecb9ed39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('infected', sa.Boolean(), nullable=False),
    sa.Column('infected_by', sa.Integer(), nullable=True),
    sa.Column('severity_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['infected_by'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crops')
    # ### end Alembic commands ###
